# Generated by Django 5.2.4 on 2025-07-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
    ]
