# Generated by Django 5.2.4 on 2025-07-25 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_core', '0005_alter_tenantinfo_slug'),
        ('users', '0002_userprofile_is_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='chatbot_core.tenantinfo'),
        ),
    ]
