# Generated by Django 5.2.4 on 2025-07-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_tenantprofile_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='last_jwt_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='last_token_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
