# Generated by Django 5.2.3 on 2025-06-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenantinfo',
            old_name='name',
            new_name='display_name',
        ),
        migrations.AddField(
            model_name='tenantinfo',
            name='business_type',
            field=models.CharField(choices=[('cafe', 'Cafe'), ('yoga', 'Yoga Studio'), ('retail', 'Retail Store')], default='cafe', max_length=20),
        ),
    ]
