# Generated by Django 5.2.3 on 2025-06-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_core', '0002_rename_name_tenantinfo_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantinfo',
            name='business_type',
            field=models.CharField(choices=[('cafe', 'Cafe'), ('studio', 'Studio'), ('retail', 'Retail Store'), ('solutions', 'Solution products')], default='cafe', max_length=20),
        ),
    ]
