# Generated by Django 5.2.3 on 2025-06-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_core', '0003_alter_tenantinfo_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantinfo',
            name='api_key',
            field=models.CharField(blank=True, editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='tenantinfo',
            name='business_type',
            field=models.CharField(choices=[('cafe', 'Cafe'), ('studio', 'Yoga Studio'), ('retail', 'Retail Store'), ('solutions', 'Solution Products')], default='cafe', max_length=20),
        ),
    ]
