# Generated by Django 5.2.3 on 2025-06-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_core', '0004_tenantinfo_api_key_alter_tenantinfo_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantinfo',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
