# Generated by Django 5.2.4 on 2025-07-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_core', '0005_alter_tenantinfo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantinfo',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenantinfo',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
