# Generated by Django 5.2.4 on 2025-07-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_core', '0006_tenantinfo_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantinfo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantinfo',
            name='telegram_bot_token',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tenantinfo',
            name='whatsapp_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
