# Generated by Django 5.2.4 on 2025-07-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_core', '0007_tenantinfo_is_active_tenantinfo_telegram_bot_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantinfo',
            name='allowed_domains',
            field=models.JSONField(default=list),
        ),
    ]
