# Generated by Django 5.2.5 on 2025-08-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_core', '0008_tenantinfo_allowed_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantinfo',
            name='meta',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='tenantinfo',
            name='petpooja_access_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tenantinfo',
            name='petpooja_app_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tenantinfo',
            name='petpooja_app_secret',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tenantinfo',
            name='petpooja_rest_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
