# Generated by Django 5.2.6 on 2025-09-21 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_core', '0010_tenantinfo_approval_status_tenantinfo_review_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantJSONDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('dtype', models.CharField(choices=[('knowledge', 'Knowledge'), ('prompt_intents', 'Prompt Intents')], max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='json_docs', to='chatbot_core.tenantinfo')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'dtype'], name='chatbot_cor_tenant__f9c186_idx')],
                'unique_together': {('tenant', 'dtype')},
            },
        ),
    ]
