# Generated by Django 5.2.6 on 2025-09-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_core', '0011_tenantjsondoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantjsondoc',
            name='dtype',
            field=models.CharField(choices=[('knowledge', 'Knowledge'), ('response_intents', 'Response Intents'), ('intent_classification', 'Intent Classification')], max_length=32),
        ),
    ]
