# Generated by Django 5.2.6 on 2025-09-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_core', '0012_alter_tenantjsondoc_dtype'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tenantjsondoc',
            unique_together={('tenant', 'dtype', 'name')},
        ),
        migrations.AddIndex(
            model_name='tenantjsondoc',
            index=models.Index(fields=['tenant', 'dtype', 'name'], name='chatbot_cor_tenant__793f96_idx'),
        ),
    ]
