# Generated by Django 5.2.6 on 2025-09-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_core', '0013_alter_tenantjsondoc_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tenantjsondoc',
            name='chatbot_cor_tenant__793f96_idx',
        ),
        migrations.RenameField(
            model_name='tenantjsondoc',
            old_name='name',
            new_name='intent',
        ),
        migrations.AlterUniqueTogether(
            name='tenantjsondoc',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tenantjsondoc',
            name='sub_intent',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='tenantjsondoc',
            unique_together={('tenant', 'dtype', 'intent', 'sub_intent')},
        ),
        migrations.AddIndex(
            model_name='tenantjsondoc',
            index=models.Index(fields=['tenant', 'dtype', 'intent', 'sub_intent'], name='chatbot_cor_tenant__b7091e_idx'),
        ),
    ]
