# Generated by Django 5.2.6 on 2025-09-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_core', '0014_remove_tenantjsondoc_chatbot_cor_tenant__793f96_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tenantjsondoc',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='tenantjsondoc',
            name='intent',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='tenantjsondoc',
            name='sub_intent',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AddConstraint(
            model_name='tenantjsondoc',
            constraint=models.UniqueConstraint(fields=('tenant', 'dtype', 'intent', 'sub_intent'), name='uniq_tenant_dtype_intent_subintent'),
        ),
    ]
