# Generated by Django 5.2.7 on 2025-11-02 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_core', '0015_alter_tenantjsondoc_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanticCacheEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sig', models.CharField(db_index=True, max_length=64)),
                ('scope', models.CharField(db_index=True, max_length=128)),
                ('kb_fp', models.CharField(db_index=True, max_length=64)),
                ('normalized_query', models.TextField()),
                ('response', models.JSONField()),
                ('system_id', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('params_hash', models.CharField(max_length=128)),
                ('language', models.CharField(default='en', max_length=8)),
                ('domain', models.CharField(default='static', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_hit', models.DateTimeField(auto_now=True)),
                ('hit_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FaissVector',
            fields=[
                ('cache_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='chatbot_core.semanticcacheentry')),
                ('dim', models.IntegerField(default=384)),
                ('vector', models.BinaryField()),
            ],
        ),
        migrations.AddIndex(
            model_name='semanticcacheentry',
            index=models.Index(fields=['sig'], name='chatbot_cor_sig_e935db_idx'),
        ),
        migrations.AddIndex(
            model_name='semanticcacheentry',
            index=models.Index(fields=['domain', 'created_at'], name='chatbot_cor_domain_2ba04f_idx'),
        ),
    ]
