# Generated by Django 5.2.17 on 2026-09-21 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_core', '0019_tenantruntimeconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantinfo',
            name='petpooja_access_token',
        ),
        migrations.RemoveField(
            model_name='tenantinfo',
            name='petpooja_app_key',
        ),
        migrations.RemoveField(
            model_name='tenantinfo',
            name='petpooja_app_secret',
        ),
        migrations.RemoveField(
            model_name='tenantinfo',
            name='petpooja_rest_id',
        ),
    ]
