# Generated by Django 5.2.17 on 2026-09-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_core', '0020_remove_tenantinfo_petpooja_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantinfo',
            name='business_type',
            field=models.CharField(choices=[('cafe', 'Café / restaurant')], default='cafe', max_length=20),
        ),
    ]
