# Generated by Django 5.2.17 on 2026-10-10 09:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_core', '0024_tenantinfo_city_tenantinfo_city_place_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanticCacheState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='semanticcacheentry',
            name='embedding_id',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='semanticcacheentry',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='semanticcacheentry',
            name='partition',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='semanticcacheentry',
            name='size_bytes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='semanticcacheentry',
            index=models.Index(fields=['partition', 'expires_at'], name='semantic_partition_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='semanticcacheentry',
            index=models.Index(fields=['expires_at'], name='semantic_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='semanticcacheentry',
            index=models.Index(fields=['last_hit', 'id'], name='semantic_lru_idx'),
        ),
        migrations.AddConstraint(
            model_name='semanticcacheentry',
            constraint=models.UniqueConstraint(condition=models.Q(('partition', ''), _negated=True), fields=('partition', 'sig'), name='semantic_partition_sig_uniq'),
        ),
    ]
