# Generated by Django 5.2.17 on 2026-09-20 17:23

import commerce.policy
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot_core', '0019_tenantruntimeconfiguration'),
        ('orders', '0018_checkout_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chatbot_core.tenantinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=64)),
                ('role', models.CharField(choices=[('pos', 'POS'), ('payment', 'Payment')], max_length=16)),
                ('account_id', models.CharField(max_length=200)),
                ('environment', models.CharField(choices=[('test', 'Test'), ('live', 'Live')], default='test', max_length=16)),
                ('active', models.BooleanField(default=False)),
                ('capabilities', models.JSONField(default=list)),
                ('secret_ref', models.CharField(help_text='Key in settings.COMMERCE_ADAPTER_SECRETS; never the secret itself.', max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.location')),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('policy', models.JSONField(default=commerce.policy.default_policy, validators=[commerce.policy.validate_policy])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='chatbot_core.tenantinfo')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.location')),
            ],
        ),
        migrations.CreateModel(
            name='AcceptedOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=3)),
                ('exponent', models.PositiveSmallIntegerField(default=2)),
                ('total_minor', models.PositiveBigIntegerField()),
                ('snapshot', models.JSONField()),
                ('snapshot_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('state', models.CharField(default='awaiting_payment', max_length=32)),
                ('pos_state', models.CharField(default='not_requested', max_length=32)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commerce_record', to='orders.order')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_minor', models.PositiveBigIntegerField()),
                ('captured_minor', models.PositiveBigIntegerField(default=0)),
                ('refunded_minor', models.PositiveBigIntegerField(default=0)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('external_id', models.CharField(blank=True, max_length=200, null=True)),
                ('sequence', models.PositiveBigIntegerField(default=0)),
                ('checkout_url', models.URLField(blank=True, max_length=2000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='commerce.acceptedorder')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.connection')),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='commerce.acceptedorder')),
            ],
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('quantity', 'Quantity'), ('availability', 'Availability')], default='quantity', max_length=16)),
                ('on_hand', models.PositiveIntegerField(default=0)),
                ('reserved', models.PositiveIntegerField(default=0)),
                ('pending_consumed', models.PositiveIntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('sequence', models.PositiveBigIntegerField(default=0)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('addon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.addonitem')),
                ('authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='commerce.connection')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.menuitem')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.location')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.menuitemvariant')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('state', models.CharField(default='held', max_length=16)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('accepted_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='commerce.acceptedorder')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.stockitem')),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=64)),
                ('dedupe_key', models.CharField(max_length=200)),
                ('payload', models.JSONField()),
                ('status', models.CharField(db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(db_index=True)),
                ('lease_token', models.UUIDField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commands', to='commerce.acceptedorder')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.connection')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('connection', 'dedupe_key'), name='commerce_command_dedupe')],
            },
        ),
        migrations.CreateModel(
            name='ExternalMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=32)),
                ('canonical_id', models.CharField(max_length=100)),
                ('external_id', models.CharField(max_length=200)),
                ('scope', models.CharField(blank=True, default='', max_length=200)),
                ('revision', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.connection')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('connection', 'kind', 'scope', 'canonical_id'), name='commerce_mapping_canonical'), models.UniqueConstraint(fields=('connection', 'kind', 'scope', 'external_id'), name='commerce_mapping_external')],
            },
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=200)),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.connection')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('connection', 'event_id'), name='commerce_inbox_event')],
            },
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='commerce_location_code'),
        ),
        migrations.AddConstraint(
            model_name='connection',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('location', 'role'), name='commerce_active_role'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('connection', 'external_id'), name='commerce_payment_external'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('accepted_order',), name='commerce_one_payment_attempt'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('refunded_minor__lte', models.F('captured_minor'))), name='commerce_refund_lte_capture'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationissue',
            constraint=models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True)), fields=('accepted_order', 'code'), name='commerce_open_issue'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('addon__isnull', True), ('item__isnull', False), ('variant__isnull', True)), models.Q(('addon__isnull', True), ('item__isnull', True), ('variant__isnull', False)), models.Q(('addon__isnull', False), ('item__isnull', True), ('variant__isnull', True)), _connector='OR'), name='commerce_stock_one_subject'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.UniqueConstraint(fields=('location', 'item'), name='commerce_stock_item'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.UniqueConstraint(fields=('location', 'variant'), name='commerce_stock_variant'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.UniqueConstraint(fields=('location', 'addon'), name='commerce_stock_addon'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('accepted_order', 'stock'), name='commerce_reservation_stock'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='commerce_reservation_positive'),
        ),
    ]
