# Generated by Django 5.2.17 on 2026-09-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_protect_accepted_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='secret_fingerprint',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
