# Generated by Django 5.2.17 on 2026-09-21 18:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_core', '0021_alter_tenantinfo_business_type'),
        ('commerce', '0004_register_adapter_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('local', 'Local menu'), ('external', 'External menu')], default='local', max_length=16)),
                ('generation', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('max_age_seconds', models.PositiveIntegerField(default=900)),
                ('sequence', models.PositiveBigIntegerField(default=0)),
                ('revision', models.CharField(blank=True, max_length=100)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='commerce.connection')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chatbot_core.tenantinfo')),
            ],
        ),
    ]
