#!/usr/bin/env python3
"""Guided Compose setup. Requires only Python's standard library on the host."""
import argparse
import getpass
import json
import os
from pathlib import Path
import re
import secrets
import shutil
import subprocess
import sys
import time
from urllib.parse import urlsplit

ROOT = Path(__file__).resolve().parents[1]
SECRET_KEYS = ("SECRET_KEY", "JWT_SECRET", "POSTGRES_PASSWORD")


def fail(message):
    raise ValueError(message)


def quoted(value):
    # Compose single quotes preserve $, # and backslashes without interpolation.
    if any(char in value for char in "\r\n'"):
        fail("Configuration values must be single-line and cannot contain a single quote.")
    return "'" + value + "'"


def configure(path, production, interactive):
    if path.exists():
        print(f"Using existing {path.name}; credentials and settings are preserved.", flush=True)
        return
    values = {key: secrets.token_urlsafe(36) for key in SECRET_KEYS}
    values["OPENAI_API_KEY"] = os.environ.get("OPENAI_API_KEY", "")
    if interactive and not values["OPENAI_API_KEY"]:
        values["OPENAI_API_KEY"] = getpass.getpass("OpenAI API key (Enter to configure later): ").strip()
    values["STUDIO_ENV_FILE"] = "/dev/null"
    if production:
        if not interactive:
            fail("Production configuration needs a domain. Run interactively, or supply an existing --env-file.")
        domain = input("Production domain (for example, cafe.your-domain.com): ").strip().lower()
        if not re.fullmatch(r"[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?", domain) or "." not in domain:
            fail("Enter a domain name without a scheme, port, or path.")
        cert_dir = input("Certificate directory [/etc/letsencrypt]: ").strip() or "/etc/letsencrypt"
        values.update(PUBLIC_URL=f"https://{domain}", ALLOWED_HOSTS=domain,
                      NGINX_SERVER_NAME=domain, TLS_CERT_NAME=domain,
                      LETSENCRYPT_DIR=str(Path(cert_dir).expanduser().resolve()),
                      HTTP_BIND="0.0.0.0", HTTP_PORT="80", DEBUG="false")
    else:
        password = os.environ.get("DEMO_OWNER_PASSWORD", "")
        if interactive and not password:
            password = getpass.getpass("Demo owner password (12+ characters; Enter to generate): ")
        values["DEMO_OWNER_PASSWORD"] = password or secrets.token_urlsafe(18)
        if len(values["DEMO_OWNER_PASSWORD"]) < 12:
            fail("The demo owner password must be at least 12 characters.")
    lines = ["# Production configuration." if production else "# Local demo configuration.",
             "# Generated by scripts/setup.py. Keep this file private; reruns preserve it."]
    for line in (ROOT / ".env.example").read_text().splitlines():
        if line.startswith("# Copy to .env."):
            continue
        key = line.split("=", 1)[0]
        if key in values:
            line = f"{key}={quoted(values.pop(key))}"
        lines.append(line)
    lines.extend(f"{key}={quoted(value)}" for key, value in values.items())
    # Exclusive creation: never replace a configuration that another process created.
    descriptor = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(descriptor, "w") as handle:
        handle.write("\n".join(lines) + "\n")
    print(f"Created {path.name} with private file permissions and generated secrets.", flush=True)


def environment(path, project):
    env = dict(os.environ)
    # The selected file, not unrelated exported application/Compose settings,
    # must determine the stack. Keep PATH, Docker context, proxy settings, etc.
    for text in ((ROOT / ".env.example").read_text(), path.read_text()):
        for key in re.findall(r"^(?:export\s+)?([A-Za-z_][A-Za-z_0-9]*)=", text, re.MULTILINE):
            env.pop(key, None)
    for key in ("COMPOSE_FILE", "COMPOSE_PROFILES", "COMPOSE_ENV_FILES"):
        env.pop(key, None)
    env.update(APP_ENV_FILE=str(path), COMPOSE_PROJECT_NAME=project, APP_IMAGE=f"{project}:local")
    return env


class Stack:
    def __init__(self, path, project, production):
        self.path = path
        self.env = environment(path, project)
        self.command = ["docker", "compose", "--project-name", project,
                        "--env-file", str(path), "-f", "docker-compose.yml", "-f",
                        "docker-compose.tls.yml" if production else "docker-compose.dev.yml"]

    def run(self, *args, capture=False, check=True):
        return subprocess.run([*self.command, *args], cwd=ROOT,
                              env=self.env, text=True,
                              capture_output=capture, check=check)

    def configuration(self):
        result = self.run("config", "--format", "json", capture=True, check=False)
        if result.returncode:
            # Compose error output can include expanded environment values.
            fail(f"Compose could not resolve {self.path.name}. Check its syntax and required settings.")
        return json.loads(result.stdout)


def check_docker():
    if not shutil.which("docker"):
        fail("Install Docker with the Compose v2 plugin, then rerun setup.")
    for args in (["docker", "compose", "version"], ["docker", "info"]):
        result = subprocess.run(args, capture_output=True, text=True)
        if result.returncode:
            fail("Docker Compose and a running Docker engine are required. Start Docker, then rerun setup.")


def validate(config, production):
    services = config["services"]
    app = services["web"]["environment"]
    for key in SECRET_KEYS:
        value = str(app.get(key) or "")
        if not value or value.startswith("change-me"):
            fail(f"Set {key} in the selected environment file before continuing.")
    if services["db"]["environment"].get("POSTGRES_PASSWORD") != app["POSTGRES_PASSWORD"]:
        fail("Database and application passwords must match.")
    origin = urlsplit(app.get("PUBLIC_URL", ""))
    if production:
        if (origin.scheme != "https" or not origin.hostname or
                origin.hostname in {"localhost", "127.0.0.1", "::1"} or
                origin.username or origin.password or origin.path not in {"", "/"} or
                origin.query or origin.fragment or origin.port not in {None, 443}):
            fail("Production PUBLIC_URL must be an HTTPS origin on your domain (standard port 443).")
        if str(app.get("DEBUG", "false")).lower() not in {"false", "0", "no"}:
            fail("Production requires DEBUG=false.")
        if app.get("DJANGO_SETTINGS_MODULE", "studio_desk.settings") != "studio_desk.settings":
            fail("Production requires studio_desk.settings, with evaluation disabled.")
        if origin.hostname not in str(app.get("ALLOWED_HOSTS", "")).split(","):
            fail("Add the production domain to ALLOWED_HOSTS.")
        nginx = services["nginx"]
        if nginx["environment"].get("NGINX_SERVER_NAME") != origin.hostname:
            fail("NGINX_SERVER_NAME must match the production domain.")
        cert_name = nginx["environment"].get("TLS_CERT_NAME", "")
        if not re.fullmatch(r"[A-Za-z0-9_.-]+", cert_name) or cert_name in {".", ".."}:
            fail("TLS_CERT_NAME must be a certificate directory name.")
        mount = next(v["source"] for v in nginx["volumes"] if v["target"] == "/etc/letsencrypt")
        for name in ("fullchain.pem", "privkey.pem"):
            if not (Path(mount) / "live" / cert_name / name).is_file():
                fail(f"Install TLS certificates under {mount}/live/{cert_name}/ before deploying (missing {name}).")
        if not app.get("OPENAI_API_KEY"):
            fail("Set OPENAI_API_KEY in the production environment file for live chat.")
    else:
        if origin.scheme != "http" or origin.hostname not in {"localhost", "127.0.0.1"}:
            fail("Local setup requires a loopback HTTP PUBLIC_URL.")
        if any(port.get("host_ip") != "127.0.0.1" for port in services["nginx"].get("ports", [])):
            fail("Local setup requires HTTP_BIND=127.0.0.1.")
        if len(str(app.get("DEMO_OWNER_PASSWORD") or "")) < 12:
            fail("Set DEMO_OWNER_PASSWORD to at least 12 characters in the local environment file.")
    return app


def start_local(stack, app):
    print("Building and starting the local café and mock services…", flush=True)
    stack.run("up", "--build", "-d", "--wait", "--wait-timeout", "180")
    stack.run("exec", "-T", "web", "python", "manage.py", "seed_cafe_demo")
    stack.run("exec", "-T", "web", "python", "manage.py", "smoke_installation")
    origin = app["PUBLIC_URL"].rstrip("/")
    print(f"\nDashboard: {origin}/accounts/login/\nUsername: demo-owner\n"
          f"Password: DEMO_OWNER_PASSWORD in {stack.path.name} (existing accounts keep their password)\n"
          f"Chat: {origin}/chat-page/?tenant=demo-cafe\nTry: What is on the menu?", flush=True)
    if not app.get("OPENAI_API_KEY"):
        print(f"Add OPENAI_API_KEY to {stack.path.name} and rerun setup to enable chat.")
    print("The interactive café demonstrates menu and information answers; checkout is disabled.")


def run_demo(stack, config):
    # Reuse the existing runner, including disposable tenants, provider simulators,
    # evidence retention, workload caps, scoring and report rendering.
    command = [sys.executable, str(ROOT / "scripts/evaluate-dev")]
    options = ["--config", config, "--output", "/var/tmp/studio-eval"]
    print("Waiting for evaluation readiness (adapter, worker and scheduler)…", flush=True)
    deadline = time.monotonic() + 120
    while True:
        result = subprocess.run([*command, "preflight", *options], cwd=ROOT,
                                env=stack.env, capture_output=True, text=True)
        if result.returncode == 0:
            break
        if time.monotonic() >= deadline:
            print(result.stdout, end="")
            print(result.stderr, end="", file=sys.stderr)
            fail("Evaluation preflight failed; no live chat was sent.")
        time.sleep(5)
    print("Running the demo: payment/POS services are simulated; model calls use your API key.", flush=True)
    subprocess.run([*command, "run", *options, "--allow-live-chat", "--report"],
                   cwd=ROOT, env=stack.env, check=True)
    print("Read the report's execution status and evaluation verdict; completion alone is not a pass.")


def deploy(stack):
    print("Building production images…", flush=True)
    stack.run("build")
    stack.run("up", "-d", "--wait", "db", "redis")
    # Stop application traffic/writers before migrations on repeat deployments.
    stack.run("stop", "nginx", "web", "celery_worker", "celery_beat")
    stack.run("run", "--rm", "--no-deps", "init")
    subprocess.run(["bash", str(ROOT / "scripts/start_production.sh"),
                    "--wait", "--wait-timeout", "180"], cwd=ROOT, env=stack.env, check=True)
    print("Production services are running. Create the operator account:", flush=True)
    import shlex
    print(shlex.join(["env", f"APP_ENV_FILE={stack.path}", f"APP_IMAGE={stack.env['APP_IMAGE']}",
                      *stack.command, "exec", "web", "python", "manage.py", "createsuperuser"]))
    print("Then create and configure your restaurant. No demo tenant or mock services were installed.")


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mode", nargs="?", choices=("local", "demo", "production"), default="local")
    parser.add_argument("--env-file", type=Path, help="Existing configuration, or a new file to generate")
    parser.add_argument("--project-name", help="Stable Compose project name; changing it selects new volumes")
    parser.add_argument("--no-input", action="store_true", help="Do not prompt; generate local credentials")
    parser.add_argument("--configure-only", action="store_true", help="Create configuration without starting services")
    parser.add_argument("--allow-live-chat", action="store_true", help="Allow paid model calls for the mock-service demo")
    parser.add_argument("--config", default="evaluate/configs/smoke.json", help="Demo evaluation preset")
    args = parser.parse_args(argv)
    production = args.mode == "production"
    path = args.env_file or ROOT / (".env.production" if production else ".env.demo")
    path = path.expanduser().resolve()
    project = args.project_name or ("shop-assistant-production" if production else "shop-assistant-demo")
    if args.mode == "demo" and not args.allow_live_chat:
        parser.error("demo requires --allow-live-chat: commerce is mocked, but model calls incur API usage")
    configure(path, production, not args.no_input and sys.stdin.isatty())
    if args.configure_only:
        return 0
    check_docker()
    stack = Stack(path, project, production)
    app = validate(stack.configuration(), production)
    if production:
        deploy(stack)
    else:
        if args.mode == "demo" and not app.get("OPENAI_API_KEY"):
            fail(f"Add OPENAI_API_KEY to {path.name} before running the end-to-end demo.")
        start_local(stack, app)
        if args.mode == "demo":
            run_demo(stack, args.config)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (ValueError, OSError) as exc:
        print(f"Setup stopped: {exc}", file=sys.stderr)
        raise SystemExit(1)
    except subprocess.CalledProcessError as exc:
        print(f"Setup stopped: a command failed (exit {exc.returncode}). Fix the reported error and rerun; volumes are preserved.", file=sys.stderr)
        raise SystemExit(exc.returncode)
    except (KeyboardInterrupt, EOFError):
        print("\nSetup cancelled. Existing configuration and volumes are preserved.", file=sys.stderr)
        raise SystemExit(130)
