#!/usr/bin/env python3
"""Guided Compose setup using Python's standard library; production also needs curl and OpenSSL."""
import argparse
import errno
import getpass
import json
import os
from pathlib import Path
import re
import secrets
import shlex
import shutil
import socket
import ssl
import subprocess
import sys
import time
from urllib.parse import urlsplit

ROOT = Path(__file__).resolve().parents[1]
SECRET_KEYS = ("SECRET_KEY", "JWT_SECRET", "POSTGRES_PASSWORD")
LOG_PATH = None


def report(message, error=False):
    """Log setup decisions only: never expanded configuration or application logs."""
    print(message, file=sys.stderr if error else sys.stdout, flush=True)
    if LOG_PATH:
        try:
            with LOG_PATH.open("a") as log:
                log.write(f"{time.strftime('%Y-%m-%dT%H:%M:%S%z')} {message}\n")
        except OSError:
            print("Could not append to the setup log; check disk space and permissions.", file=sys.stderr)


def fail(message):
    raise ValueError(message)


def quoted(value):
    # Compose single quotes preserve $, # and backslashes without interpolation.
    if any(char in value for char in "\r\n'"):
        fail("Configuration values must be single-line and cannot contain a single quote.")
    return "'" + value + "'"


def configure(path, production, interactive):
    if path.exists():
        report(f"Using existing {path.name}; credentials and settings are preserved.")
        return
    values = {key: secrets.token_urlsafe(36) for key in SECRET_KEYS}
    values["OPENAI_API_KEY"] = os.environ.get("OPENAI_API_KEY", "")
    if interactive and not values["OPENAI_API_KEY"]:
        values["OPENAI_API_KEY"] = getpass.getpass("OpenAI API key (Enter to configure later): ").strip()
    values["STUDIO_ENV_FILE"] = "/dev/null"
    if production:
        if not interactive:
            fail("Production configuration needs a domain. Run interactively, or supply an existing --env-file.")
        domain = input("Production domain (for example, cafe.your-domain.com): ").strip().lower()
        if not re.fullmatch(r"[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?", domain) or "." not in domain:
            fail("Enter a domain name without a scheme, port, or path.")
        cert_dir = input("Certificate directory [/etc/letsencrypt]: ").strip() or "/etc/letsencrypt"
        values.update(PUBLIC_URL=f"https://{domain}", ALLOWED_HOSTS=domain,
                      NGINX_SERVER_NAME=domain, TLS_CERT_NAME=domain,
                      LETSENCRYPT_DIR=str(Path(cert_dir).expanduser().resolve()),
                      HTTP_BIND="0.0.0.0", HTTP_PORT="80",
                      HTTPS_BIND="0.0.0.0", HTTPS_PORT="443", DEBUG="false")
    else:
        password = os.environ.get("DEMO_OWNER_PASSWORD", "")
        if interactive and not password:
            password = getpass.getpass("Demo owner password (12+ characters; Enter to generate): ")
        values["DEMO_OWNER_PASSWORD"] = password or secrets.token_urlsafe(18)
        if len(values["DEMO_OWNER_PASSWORD"]) < 12:
            fail("The demo owner password must be at least 12 characters.")
    lines = ["# Production configuration." if production else "# Local demo configuration.",
             "# Generated by scripts/setup.py. Keep this file private; reruns preserve it."]
    for line in (ROOT / ".env.example").read_text().splitlines():
        if line.startswith("# Copy to .env."):
            continue
        key = line.split("=", 1)[0]
        if key in values:
            line = f"{key}={quoted(values.pop(key))}"
        lines.append(line)
    lines.extend(f"{key}={quoted(value)}" for key, value in values.items())
    # Exclusive creation: never replace a configuration that another process created.
    descriptor = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(descriptor, "w") as handle:
        handle.write("\n".join(lines) + "\n")
    report(f"Created {path.name} with private file permissions and generated secrets.")


def environment(path, project):
    env = dict(os.environ)
    # The selected file, not unrelated exported application/Compose settings,
    # must determine the stack. Keep PATH, Docker context, proxy settings, etc.
    for text in ((ROOT / ".env.example").read_text(), path.read_text()):
        for key in re.findall(r"^(?:export\s+)?([A-Za-z_][A-Za-z_0-9]*)=", text, re.MULTILINE):
            env.pop(key, None)
    for key in ("COMPOSE_FILE", "COMPOSE_PROFILES", "COMPOSE_ENV_FILES"):
        env.pop(key, None)
    env.update(APP_ENV_FILE=str(path), COMPOSE_PROJECT_NAME=project, APP_IMAGE=f"{project}:local")
    return env


class Stack:
    def __init__(self, path, project, production):
        self.path = path
        self.env = environment(path, project)
        self.command = ["docker", "compose", "--project-name", project,
                        "--env-file", str(path), "-f", "docker-compose.yml", "-f",
                        "docker-compose.tls.yml" if production else "docker-compose.dev.yml"]

    def run(self, *args, capture=False, check=True):
        return subprocess.run([*self.command, *args], cwd=ROOT,
                              env=self.env, text=True,
                              capture_output=capture, check=check)

    def configuration(self):
        result = self.run("config", "--format", "json", capture=True, check=False)
        if result.returncode:
            # Compose error output can include expanded environment values.
            fail(f"Compose could not resolve {self.path.name}. Check its syntax and required settings.")
        return json.loads(result.stdout)


def check_docker():
    if not shutil.which("docker"):
        fail("Install Docker with the Compose v2 plugin, then rerun setup.")
    for args in (["docker", "compose", "version"], ["docker", "info"]):
        result = subprocess.run(args, capture_output=True, text=True)
        if result.returncode:
            fail("Docker Compose and a running Docker engine are required. Start Docker, then rerun setup.")


def validate(config, production):
    services = config["services"]
    app = services["web"]["environment"]
    for key in SECRET_KEYS:
        value = str(app.get(key) or "")
        if not value or value.startswith("change-me"):
            fail(f"Set {key} in the selected environment file before continuing.")
    if services["db"]["environment"].get("POSTGRES_PASSWORD") != app["POSTGRES_PASSWORD"]:
        fail("Database and application passwords must match.")
    origin = urlsplit(app.get("PUBLIC_URL", ""))
    if production:
        if (origin.scheme != "https" or not origin.hostname or
                origin.hostname in {"localhost", "127.0.0.1", "::1"} or
                origin.username or origin.password or origin.path not in {"", "/"} or
                origin.query or origin.fragment or origin.port not in {None, 443}):
            fail("Production PUBLIC_URL must be an HTTPS origin on your domain (standard port 443).")
        if str(app.get("DEBUG", "false")).lower() not in {"false", "0", "no"}:
            fail("Production requires DEBUG=false.")
        if app.get("DJANGO_SETTINGS_MODULE", "studio_desk.settings") != "studio_desk.settings":
            fail("Production requires studio_desk.settings, with evaluation disabled.")
        if origin.hostname not in str(app.get("ALLOWED_HOSTS", "")).split(","):
            fail("Add the production domain to ALLOWED_HOSTS.")
        nginx = services["nginx"]
        if nginx["environment"].get("NGINX_SERVER_NAME") != origin.hostname:
            fail("NGINX_SERVER_NAME must match the production domain.")
        cert_name = nginx["environment"].get("TLS_CERT_NAME", "")
        if not re.fullmatch(r"[A-Za-z0-9_.-]+", cert_name) or cert_name in {".", ".."}:
            fail("TLS_CERT_NAME must be a certificate directory name.")
        mount = next(v["source"] for v in nginx["volumes"] if v["target"] == "/etc/letsencrypt")
        for name in ("fullchain.pem", "privkey.pem"):
            if not (Path(mount) / "live" / cert_name / name).is_file():
                command = shlex.join(["sudo", "certbot", "certonly", "--standalone",
                                      "--config-dir", mount, "--cert-name", cert_name,
                                      "-d", origin.hostname])
                fail(f"TLS certificate missing {name} under {mount}/live/{cert_name}/. "
                     f"For a new server, point DNS here and free port 80, then run:\n{command}\n"
                     "If a web server already uses port 80, use its webroot instead. "
                     "See docs/operations/production.md#certificates.")
        if not app.get("OPENAI_API_KEY"):
            fail("Set OPENAI_API_KEY in the production environment file for live chat.")
    else:
        if origin.scheme != "http" or origin.hostname not in {"localhost", "127.0.0.1"}:
            fail("Local setup requires a loopback HTTP PUBLIC_URL.")
        if any(port.get("host_ip") != "127.0.0.1" for port in services["nginx"].get("ports", [])):
            fail("Local setup requires HTTP_BIND=127.0.0.1.")
        if len(str(app.get("DEMO_OWNER_PASSWORD") or "")) < 12:
            fail("Set DEMO_OWNER_PASSWORD to at least 12 characters in the local environment file.")
    return app


def check_certificate(config):
    nginx = config["services"]["nginx"]
    domain = urlsplit(config["services"]["web"]["environment"]["PUBLIC_URL"]).hostname
    root = next(v["source"] for v in nginx["volumes"] if v["target"] == "/etc/letsencrypt")
    directory = Path(root) / "live" / nginx["environment"]["TLS_CERT_NAME"]
    cert = directory / "fullchain.pem"
    try:
        context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
        context.load_cert_chain(str(cert), str(directory / "privkey.pem"), password=lambda: "")
    except (OSError, ssl.SSLError):
        fail("Cannot load the TLS certificate and matching private key. Check PEM contents, "
             "file permissions and that the key is unencrypted. See docs/operations/production.md#certificates.")
    dates = subprocess.run(["openssl", "x509", "-in", str(cert), "-noout", "-dates"],
                           capture_output=True, text=True, timeout=10)
    try:
        values = dict(line.split("=", 1) for line in dates.stdout.splitlines())
        start = ssl.cert_time_to_seconds(values["notBefore"])
        end = ssl.cert_time_to_seconds(values["notAfter"])
        if dates.returncode:
            raise ValueError
    except (KeyError, ValueError):
        fail("Cannot read TLS certificate dates with OpenSSL.")
    now = time.time()
    if end <= now:
        fail("TLS certificate has expired. Renew it before deploying; "
             "see docs/operations/production.md#renewal. Also check the server clock.")
    if start > now:
        fail("TLS certificate is not valid yet. Check the server clock and certificate dates.")
    hostname = subprocess.run(["openssl", "x509", "-in", str(cert), "-noout", "-checkhost", domain],
                              capture_output=True, text=True, timeout=10)
    # OpenSSL 3.0 can exit zero even when -checkhost reports a mismatch.
    # Require its explicit positive result as well as a successful command.
    if hostname.returncode or hostname.stdout.strip() != f"Hostname {domain} does match certificate":
        fail(f"TLS certificate does not cover {domain} (or OpenSSL lacks -checkhost). "
             "Use a certificate covering PUBLIC_URL; see docs/operations/production.md#certificates.")
    report(f"[OK] Certificate covers {domain}; expires {values['notAfter']}.")
    if end - now < 30 * 86400:
        report("[WARN] Certificate expires within 30 days. Check automatic renewal now.")


def docker_containers(stack):
    """Read only port ownership metadata; never return container environments."""
    result = subprocess.run(["docker", "ps", "-q"], env=stack.env,
                            capture_output=True, text=True, check=True)
    ids = result.stdout.split()
    if not ids:
        return []
    template = ('{"name":{{json .Name}},"labels":{{json .Config.Labels}},'
                '"ports":{{json .NetworkSettings.Ports}}}')
    result = subprocess.run(["docker", "inspect", "--format", template, *ids], env=stack.env,
                            capture_output=True, text=True, check=True)
    return [json.loads(line) for line in result.stdout.splitlines()]


def addresses_overlap(first, second):
    # Treat IPv6 wildcard conservatively: it may also accept IPv4 connections.
    return first in {"0.0.0.0", "::", ""} or second in {"0.0.0.0", "::", ""} or first == second


def check_ports(stack, config):
    containers = docker_containers(stack)
    for service, definition in config["services"].items():
        for port in definition.get("ports", []):
            if port.get("protocol", "tcp") != "tcp":
                continue
            address = port.get("host_ip") or "0.0.0.0"
            published = int(port["published"])
            own_addresses = set()
            own_containers = set()
            for container in containers:
                labels = container["labels"] or {}
                for container_port, bindings in (container["ports"] or {}).items():
                    if not container_port.endswith("/tcp"):
                        continue
                    for binding in bindings or []:
                        if (int(binding["HostPort"]) != published or
                                not addresses_overlap(address, binding["HostIp"])):
                            continue
                        if (labels.get("com.docker.compose.project") == stack.env["COMPOSE_PROJECT_NAME"] and
                                labels.get("com.docker.compose.service") == service):
                            own_addresses.add(binding["HostIp"] or "0.0.0.0")
                            own_containers.add(container["name"].lstrip("/"))
                        else:
                            fail(f"Port {address}:{published} is already published by {container['name']}. "
                                 "Retire that deployment only if it is no longer needed, or choose another port/proxy. "
                                 "See docs/operations/production.md#port-conflicts.")
            if address in own_addresses:
                report(f"[OK] Port {address}:{published} belongs to this deployment's {service} service.")
                continue
            if own_addresses:
                # An overlapping listener prevents probing the new address while
                # the service is running; it does not prove that address is free.
                command = shlex.join(["docker", "stop", *sorted(own_containers)])
                fail(f"Port {address}:{published} overlaps this deployment's {service} binding on "
                     f"{', '.join(sorted(own_addresses))}. Before changing the bind address, "
                     f"release its current listener with:\n{command}\n"
                     "Then rerun setup to check the requested address before deployment. "
                     "See docs/operations/production.md#port-conflicts.")
            try:
                with socket.socket(socket.AF_INET6 if ":" in address else socket.AF_INET) as probe:
                    probe.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
                    probe.bind((address, published))
            except OSError as exc:
                if exc.errno == errno.EACCES:
                    report(f"[WARN] Cannot check port {published} without elevated permissions. "
                           "Inspect listeners with sudo ss -ltnp before deploying.")
                    continue
                fail(f"Cannot bind {address}:{published} for {service}. "
                     f"Inspect listeners: sudo ss -ltnp 'sport = :{published}'. "
                     "A host Nginx/Apache service may own this port. "
                     "See docs/operations/production.md#port-conflicts.")
            report(f"[OK] Port {address}:{published} is available for {service}.")


def preflight(stack, config, production):
    report("Checking configuration and host prerequisites…")
    if production:
        for executable in ("openssl", "curl"):
            if not shutil.which(executable):
                fail(f"Install {executable} on the server before production setup.")
    app = validate(config, production)
    check_ports(stack, config)
    if production:
        check_certificate(config)
        domain = urlsplit(app["PUBLIC_URL"]).hostname
        try:
            addresses = sorted({item[4][0] for item in socket.getaddrinfo(domain, 443, type=socket.SOCK_STREAM)})
        except socket.gaierror:
            fail(f"DNS lookup failed for {domain}. Point its A record to this VPS; "
                 "check any AAAA record too. See docs/operations/production.md#dns.")
        report(f"[OK] DNS resolves {domain} to {', '.join(addresses)}. Confirm these are your server/proxy addresses.")
    report("Preflight finished; no services have been changed.")
    return app


def https_probe(url, resolve=None):
    command = ["curl", "--fail", "--silent", "--show-error", "--noproxy", "*",
               "--connect-timeout", "5", "--max-time", "10"]
    if resolve:
        command.extend(["--resolve", resolve])
    command.append(url)
    # A newly started Nginx process can need a moment after Compose reports running.
    for attempt in range(3):
        result = subprocess.run(command, capture_output=True, text=True, timeout=15)
        if result.returncode != 7 or attempt == 2:
            break
        time.sleep(2)
    if result.returncode:
        return f"curl exit {result.returncode} (7: connection, 22: HTTP error, 28: timeout, 60: TLS certificate)"
    try:
        if json.loads(result.stdout) == {"status": "ok"}:
            return None
    except ValueError:
        pass
    return "unexpected /health response"


def verify_https(stack, config):
    app = config["services"]["web"]["environment"]
    domain = urlsplit(app["PUBLIC_URL"]).hostname
    port = next(p for p in config["services"]["nginx"]["ports"] if int(p["target"]) == 443)
    address = port.get("host_ip") or "0.0.0.0"
    address = {"0.0.0.0": "127.0.0.1", "::": "::1"}.get(address, address)
    if ":" in address:
        address = f"[{address}]"
    published = port["published"]
    report("Checking local Nginx HTTPS, certificate trust and application health…")
    error = https_probe(f"https://{domain}:{published}/health", f"{domain}:{published}:{address}")
    if error:
        report("Inspect this deployment with:\n" + shlex.join([*stack.command, "ps", "-a"]))
        fail(f"Local HTTPS check failed: {error}. Check Nginx/web logs and their Docker network; "
             "see docs/operations/production.md#troubleshooting. Services were not removed.")
    report("[OK] Local HTTPS and /health passed.")
    report("Checking the public HTTPS URL from this server…")
    error = https_probe(app["PUBLIC_URL"].rstrip("/") + "/health")
    if error:
        fail(f"Local HTTPS works, but the public URL failed: {error}. "
             "Check DNS A/AAAA records, host/provider firewalls and any external proxy. "
             "Services remain running; see docs/operations/production.md#troubleshooting.")
    report("[OK] Public HTTPS and /health passed from this server. Also test from your browser.")


def start_local(stack, app):
    report("Building and starting the local café and mock services…")
    stack.run("up", "--build", "-d", "--wait", "--wait-timeout", "180")
    report("Seeding the demo café and running installation checks…")
    stack.run("exec", "-T", "web", "python", "manage.py", "seed_cafe_demo")
    stack.run("exec", "-T", "web", "python", "manage.py", "smoke_installation")
    report("[OK] Local installation checks passed.")
    origin = app["PUBLIC_URL"].rstrip("/")
    print(f"\nDashboard: {origin}/accounts/login/\nUsername: demo-owner\n"
          f"Password: DEMO_OWNER_PASSWORD in {stack.path.name} (existing accounts keep their password)\n"
          f"Chat: {origin}/chat-page/?tenant=demo-cafe\nTry: What is on the menu?", flush=True)
    if not app.get("OPENAI_API_KEY"):
        print(f"Add OPENAI_API_KEY to {stack.path.name} and rerun setup to enable chat.")
    print("The interactive café demonstrates menu and information answers; checkout is disabled.")


def run_demo(stack, config):
    # Reuse the existing runner, including disposable tenants, provider simulators,
    # evidence retention, workload caps, scoring and report rendering.
    command = [sys.executable, str(ROOT / "scripts/evaluate-dev")]
    options = ["--config", config, "--output", "/var/tmp/studio-eval"]
    print("Waiting for evaluation readiness (adapter, worker and scheduler)…", flush=True)
    deadline = time.monotonic() + 120
    while True:
        result = subprocess.run([*command, "preflight", *options], cwd=ROOT,
                                env=stack.env, capture_output=True, text=True)
        if result.returncode == 0:
            break
        if time.monotonic() >= deadline:
            print(result.stdout, end="")
            print(result.stderr, end="", file=sys.stderr)
            fail("Evaluation preflight failed; no live chat was sent.")
        time.sleep(5)
    print("Running the demo: payment/POS services are simulated; model calls use your API key.", flush=True)
    subprocess.run([*command, "run", *options, "--allow-live-chat", "--report"],
                   cwd=ROOT, env=stack.env, check=True)
    print("Read the report's execution status and evaluation verdict; completion alone is not a pass.")


def deploy(stack, config):
    report("Building production images…")
    stack.run("build")
    report("Starting database and Redis…")
    stack.run("up", "-d", "--wait", "db", "redis")
    # Stop application traffic/writers before migrations on repeat deployments.
    stack.run("stop", "nginx", "web", "celery_worker", "celery_beat")
    report("Running migrations, collecting static files and auditing tenant ownership…")
    stack.run("run", "--rm", "--no-deps", "init")
    # A failed initial port bind can leave an old proxy without a network endpoint.
    # It has no writable application state; recreate it through the normal gate.
    report("Replacing the stopped Nginx container to refresh its network and port mappings…")
    stack.run("rm", "-f", "-s", "nginx")
    report("Starting production services…")
    subprocess.run(["bash", str(ROOT / "scripts/start_production.sh"),
                    "--wait", "--wait-timeout", "180"], cwd=ROOT, env=stack.env, check=True)
    verify_https(stack, config)
    report("Production HTTPS is ready.")


def operator_account(stack, interactive):
    """Offer Django's own account wizard without handling or logging passwords."""
    command = shlex.join(["env", f"APP_ENV_FILE={stack.path}", f"APP_IMAGE={stack.env['APP_IMAGE']}",
                          *stack.command, "exec", "web", "python", "manage.py", "createsuperuser"])

    def later(message):
        report(message + " HTTPS services remain running.")
        report("Create an administrator later from the checkout with:\n" + command)

    report("Checking for an active administrator account…")
    query = ("from django.contrib.auth import get_user_model; "
             "print('SETUP_OPERATOR_EXISTS=' + str(int(get_user_model().objects.filter("
             "is_superuser=True, is_active=True).exists())))")
    try:
        result = stack.run("exec", "-T", "web", "python", "manage.py", "shell", "-c", query,
                           capture=True, check=False)
        markers = set(result.stdout.splitlines())
        if result.returncode or not markers.intersection({"SETUP_OPERATOR_EXISTS=0", "SETUP_OPERATOR_EXISTS=1"}):
            later("Could not check administrator accounts.")
            return
        if "SETUP_OPERATOR_EXISTS=1" in markers:
            report("[OK] An active administrator already exists. Sign in with your existing account.")
            return
        if not interactive:
            later("No active administrator exists; account creation needs an interactive terminal.")
            return
        while True:
            answer = input("Create your administrator account now? [Y/n]: ").strip().lower()
            if answer in {"", "y", "yes"}:
                break
            if answer in {"n", "no"}:
                later("Administrator creation skipped.")
                return
            print("Enter Y to create an account or N to do this later.")
        report("Enter the username, email and password in Django's account wizard.")
        # Inherit the terminal. Django validates credentials and hides password input.
        result = stack.run("exec", "web", "python", "manage.py", "createsuperuser", check=False)
        if result.returncode:
            later("Administrator creation did not complete.")
        else:
            report("[OK] Administrator account created.")
    except (KeyboardInterrupt, EOFError):
        later("Administrator creation cancelled.")


def main(argv=None):
    global LOG_PATH
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mode", nargs="?", choices=("local", "demo", "production"), default="local")
    parser.add_argument("--env-file", type=Path, help="Existing configuration, or a new file to generate")
    parser.add_argument("--project-name", help="Stable Compose project name; changing it selects new volumes")
    parser.add_argument("--no-input", action="store_true", help="Do not prompt; generate local credentials")
    action = parser.add_mutually_exclusive_group()
    action.add_argument("--configure-only", action="store_true", help="Create configuration without starting services")
    action.add_argument("--check", action="store_true", help="Check existing configuration and prerequisites without changing services")
    parser.add_argument("--log-file", type=Path, default=ROOT / "setup.log",
                        help="Setup progress and checks (default: setup.log; excludes application logs and secrets)")
    parser.add_argument("--allow-live-chat", action="store_true", help="Allow paid model calls for the mock-service demo")
    parser.add_argument("--config", default="evaluate/configs/smoke.json", help="Demo evaluation preset")
    args = parser.parse_args(argv)
    production = args.mode == "production"
    path = args.env_file or ROOT / (".env.production" if production else ".env.demo")
    path = path.expanduser().resolve()
    project = args.project_name or ("shop-assistant-production" if production else "shop-assistant-demo")
    if args.mode == "demo" and not args.allow_live_chat:
        parser.error("demo requires --allow-live-chat: commerce is mocked, but model calls incur API usage")
    log_path = args.log_file.expanduser().resolve()
    descriptor = os.open(log_path, os.O_WRONLY | os.O_CREAT | os.O_APPEND, 0o600)
    os.close(descriptor)
    LOG_PATH = log_path
    report(f"Setup mode: {args.mode}. Configuration: {path.name}. Project: {project}.")
    report(f"Setup log: {LOG_PATH} (checks and progress; application logs stay in Docker).")
    if not production:
        report("Local/demo setup uses loopback ports and mock services. For a public VPS use: python3 scripts/setup.py production")
    if args.check and not path.exists():
        fail(f"Create {path.name} first with: python3 scripts/setup.py {args.mode} --configure-only")
    if not args.check:
        configure(path, production, not args.no_input and sys.stdin.isatty())
    if args.configure_only:
        if production:
            report("Next: point DNS to this server, free the published ports, and create TLS certificates. "
                   "Follow docs/operations/production.md, then run production --check.")
        return 0
    report("Checking Docker Engine and Compose…")
    check_docker()
    stack = Stack(path, project, production)
    config = stack.configuration()
    app = preflight(stack, config, production)
    if args.check:
        return 0
    if production:
        deploy(stack, config)
        operator_account(stack, interactive=not args.no_input and sys.stdin.isatty())
        report(f"Dashboard: {app['PUBLIC_URL'].rstrip('/')}/accounts/login/")
        report("Create and configure your restaurant, then complete certificate renewal setup "
               "in docs/operations/production.md#renewal.")
    else:
        if args.mode == "demo" and not app.get("OPENAI_API_KEY"):
            fail(f"Add OPENAI_API_KEY to {path.name} before running the end-to-end demo.")
        start_local(stack, app)
        if args.mode == "demo":
            run_demo(stack, args.config)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (ValueError, OSError) as exc:
        report(f"Setup stopped: {exc}", error=True)
        raise SystemExit(1)
    except subprocess.CalledProcessError as exc:
        report(f"Setup stopped: a command failed (exit {exc.returncode}). "
               "See the command output above and docs/operations/production.md#troubleshooting. "
               "Fix the reported error and rerun; volumes are preserved.", error=True)
        raise SystemExit(exc.returncode)
    except subprocess.TimeoutExpired:
        report("Setup stopped: a prerequisite or HTTPS check timed out. Check networking and rerun.", error=True)
        raise SystemExit(1)
    except (KeyboardInterrupt, EOFError):
        report("\nSetup cancelled. Existing configuration and volumes are preserved.", error=True)
        raise SystemExit(130)
