"""
Django settings for studio_desk project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import json
from urllib.parse import urlsplit
from django.core.exceptions import ImproperlyConfigured

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.environ.get('STUDIO_ENV_FILE', BASE_DIR / '.env'))

# Separate server-side credentials per tenant. No shared-key fallback.
WHATSAPP_APP_SECRET = os.environ.get('WHATSAPP_APP_SECRET', '')

SECRET_KEY = os.environ.get('SECRET_KEY', '')
if not SECRET_KEY:
    raise ImproperlyConfigured('SECRET_KEY must be set')
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

PUBLIC_URL = os.environ.get('PUBLIC_URL', 'https://localhost').rstrip('/')
_public = urlsplit(PUBLIC_URL)
if (_public.scheme not in ('http', 'https') or not _public.hostname
        or _public.username or _public.password or _public.path or _public.query or _public.fragment):
    raise ImproperlyConfigured('PUBLIC_URL must be an http(s) origin without credentials, path, query or fragment')
_public.port  # Validate malformed ports at startup.
ALLOWED_HOSTS = [value.strip() for value in os.getenv('ALLOWED_HOSTS', _public.hostname).split(',') if value.strip()]


OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY')
LLM_MODEL = os.environ.get("LLM_MODEL", "gpt-4.1-mini")
LLM_TRANSLATE_MODEL = os.environ.get("LLM_TRANSLATE_MODEL", "gpt-4.1-nano")
LLM_ANALYTICS_MODEL = os.environ.get("LLM_ANALYTICS_MODEL", os.environ.get("OPENAI_MODEL", "gpt-4o-mini"))
LLM_TIMEOUT = float(os.environ.get("LLM_TIMEOUT", "20"))
LLM_MAX_RETRIES = int(os.environ.get("LLM_MAX_RETRIES", "2"))
LLM_MAX_TOKENS = int(os.environ.get("LLM_MAX_TOKENS", "2048"))
MONGO_DB_URL = os.environ.get('MONGO_DB_URL')
LEGACY_TENANT_SYNC_ENABLED = os.getenv('LEGACY_TENANT_SYNC_ENABLED', 'false').lower() == 'true'

JWT_SECRET = os.environ.get("JWT_SECRET")

if not JWT_SECRET:
    raise ValueError("JWT_SECRET not set")

# Photon handles site-city autocomplete; Nominatim validates selections and postcodes.
# Use a hosted or self-hosted Photon service. No implicit public-server traffic.
PHOTON_BASE_URL = os.environ.get("PHOTON_BASE_URL", "")
# Historical evaluation controls only; customer delivery no longer uses geocoding.
LOCATION_PROVIDER = os.environ.get("LOCATION_PROVIDER", "google")
LOCATION_EMULATOR_URL = os.environ.get("LOCATION_EMULATOR_URL", "http://127.0.0.1:9080")
LOCATION_EMULATOR_TIMEOUT_SECONDS = float(os.environ.get("LOCATION_EMULATOR_TIMEOUT_SECONDS", "3"))
# City/postal directory for cafe site settings. Empty fails these lookups closed.
# Customer delivery addresses never use this directory.
NOMINATIM_BASE_URL = os.environ.get("NOMINATIM_BASE_URL", "")
NOMINATIM_API_KEY = os.environ.get("NOMINATIM_API_KEY", "")
NOMINATIM_USER_AGENT = os.environ.get(
    "NOMINATIM_USER_AGENT", "StudioDesk/1.0 (site postal directory)")
NOMINATIM_TIMEOUT_SECONDS = float(os.environ.get("NOMINATIM_TIMEOUT_SECONDS", "5"))
# Gap after request completion. Empty uses 1 second for the public host, no
# extra gap for a hosted service. The public floor cannot be set lower.
NOMINATIM_MIN_INTERVAL_SECONDS = os.environ.get("NOMINATIM_MIN_INTERVAL_SECONDS", "")
# How long one lookup may wait for exclusive dispatch before it is skipped.
NOMINATIM_MAX_QUEUE_SECONDS = float(os.environ.get("NOMINATIM_MAX_QUEUE_SECONDS", "1"))

EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'true').lower() == 'true'
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", '')
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", '')
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or 'webmaster@localhost')

# Who should receive signup alerts:
SIGNUP_ALERT_EMAIL = os.environ.get("SIGNUP_ALERT_EMAIL", EMAIL_HOST_USER or '')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True

# Application definition

INSTALLED_APPS = [
    'users.apps.OperationsAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'orders',
    'commerce',
    "rest_framework",
    'chatbot_core.apps.ChatbotCoreConfig',
    "django_celery_results",
    "django_celery_beat",
    'django_ratelimit',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "chatbot_core.middleware.ChatbotRateLimitMiddleware"
]

ROOT_URLCONF = 'studio_desk.urls'

# Redirect all HTTP to HTTPS
SECURE_SSL_REDIRECT = _public.scheme == 'https'

# Only allow cookies over HTTPS
SESSION_COOKIE_SECURE = _public.scheme == 'https'
CSRF_COOKIE_SECURE = _public.scheme == 'https'

# Set XSS and content type protections
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# Set HSTS headers
SECURE_HSTS_SECONDS = 31536000 if _public.scheme == 'https' else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Celery configuration
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://redis:6379/0')
APP_SESSION_REDIS_URL = os.getenv('APP_SESSION_REDIS_URL', 'redis://redis:6379/1')
APP_REDIS_URL = os.getenv("APP_REDIS_URL", "redis://redis:6379/2")
CELERY_RESULT_BACKEND = 'django-db'  # Provided by django-celery-results
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = "json"
CELERY_RESULT_EXTENDED = True
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1    # fairness; no hoarding
CELERY_TASK_TIME_LIMIT = 300
CELERY_TASK_SOFT_TIME_LIMIT = 270
CELERY_TASK_DEFAULT_QUEUE = "default"
CELERY_TASK_DEFAULT_EXCHANGE = "default"
CELERY_TASK_DEFAULT_ROUTING_KEY = "def.task"
CELERY_WORKER_HIJACK_ROOT_LOGGER = False
CELERY_WORKER_MAX_MEMORY_PER_CHILD = int(os.getenv("CELERY_WORKER_MAX_MEMORY_PER_CHILD", "524288"))  # KB; 0 = disabled

# Async Logging queue
STRING_QUEUE_KEY = os.getenv("STRING_QUEUE_KEY", "sd:string_queue:v1")
STRING_QUEUE_BATCH_SIZE = int(os.getenv("STRING_QUEUE_BATCH_SIZE", "100"))
STRING_QUEUE_FLUSH_SECONDS = int(os.getenv("STRING_QUEUE_FLUSH_SECONDS", "5"))  # if you later switch to a blocking worker
STRING_QUEUE_FILE = os.getenv("STRING_QUEUE_FILE", "./string_queue.log")
STRING_QUEUE_MAXLEN = int(os.getenv("STRING_QUEUE_MAXLEN", "100000"))

# Prevent clickjacking
X_FRAME_OPTIONS = 'DENY'

CSRF_TRUSTED_ORIGINS = [value.strip() for value in os.getenv('CSRF_TRUSTED_ORIGINS', PUBLIC_URL).split(',') if value.strip()]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# Use this for added security on templates (if not using Django templates for all views, can be omitted)
#CONTENT_SECURITY_POLICY = "default-src 'self';"


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'studio_desk.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'postgres'),
        'USER': os.getenv('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', ''),
        'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}

DEFAULT_LOG_LEVEL = "DEBUG" if DEBUG else "INFO"
CHATBOT_CORE_LEVEL = "DEBUG" if DEBUG else "INFO"

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        "level": DEFAULT_LOG_LEVEL,
    },
    'loggers': {
        'chatbot_core': {
            'handlers': ['console'],
            "level": CHATBOT_CORE_LEVEL,
            'propagate': False,
        },
    },
}

LOGGING["loggers"].update({
    "chatbot_core.tasks": {"handlers": ["console"], "level": "INFO", "propagate": False},
})

# Django cache (used by django_ratelimit and anything calling django.core.cache)
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": APP_REDIS_URL,  # use the Redis service name in docker-compose
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
        "TIMEOUT": None,
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.getenv('STATIC_ROOT', str(BASE_DIR / 'staticfiles'))

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Default: stores in DB
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 1 week
SESSION_SAVE_EVERY_REQUEST = True     # Optional: refresh expiry on each request

from corsheaders.defaults import default_headers

CORS_ALLOW_HEADERS = list(default_headers) + [
    "X-API-KEY",
    "Authorization",
]

CORS_ALLOW_ALL_ORIGINS = False
CORS_ORIGIN_ALLOW_ALL = False
CORS_ALLOW_CREDENTIALS = True

def cors_allow_origin_delayed(origin, request=None):
    from chatbot_core.utils import cors_allow_origin
    return cors_allow_origin(origin, request)

CORS_ORIGIN_ALLOW_FUNCTION = cors_allow_origin_delayed


import logging
logging.getLogger(__name__).warning("BROKER=%s APP_REDIS=%s", CELERY_BROKER_URL, APP_REDIS_URL)

from kombu import Exchange, Queue
CELERY_TASK_QUEUES = (
    Queue(os.getenv("EMBEDDING_QUEUE", "embeddings"), Exchange("embeddings"), routing_key="emb.*"),
    Queue("default", Exchange("default"), routing_key="def.*"),
)
CELERY_TASK_ROUTES = {
    "chatbot_core.embed_text": {"queue": os.getenv("EMBEDDING_QUEUE", "embeddings"), "routing_key": "emb.vec"},
}

CELERY_BEAT_SCHEDULE = {
    "drain-string-queue": {
        "task": "chatbot_core.drain_string_queue",
        "schedule": 30.0,  # seconds (was 2s — caused queue backlog starving other tasks)
        "options": {"queue": "default"},  # stays off your embeddings queue
    },
}

# Adapter HMAC secrets are loaded from the deployment environment, never exported.
import json as _commerce_json
COMMERCE_ADAPTER_SECRETS = _commerce_json.loads(os.environ.get('COMMERCE_ADAPTER_SECRETS', '{}'))
CELERY_BEAT_SCHEDULE = {**globals().get('CELERY_BEAT_SCHEDULE', {}),
    'commerce-reconciliation': {'task': 'commerce.tasks.reconcile_commerce', 'schedule': 60.0}}
