# Generated by Django 5.2.4 on 2025-07-24 19:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='price',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MenuItemVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size', models.CharField(choices=[('scoop', 'Scoop'), ('mini tub', 'Mini Tub'), ('regular', 'Regular'), ('family', 'Family'), ('per_quantity', 'Per Quantity')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume_ml', models.IntegerField(blank=True, null=True)),
                ('weight_grams', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='orders.menuitem')),
            ],
        ),
    ]
