# Generated by Django 5.2.4 on 2025-07-25 11:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_core', '0005_alter_tenantinfo_slug'),
        ('orders', '0002_remove_menuitem_price_menuitem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chatbot_core.tenantinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chatbot_core.tenantinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chatbot_core.tenantinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chatbot_core.tenantinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platformwebhooklog',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chatbot_core.tenantinfo'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('platform', models.CharField(choices=[('whatsapp', 'Whatsapp'), ('website', 'Website'), ('telegram', 'Telegram'), ('instagram', 'Instagram')], max_length=20)),
                ('state', models.JSONField(default=dict)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('device_info', models.JSONField(blank=True, null=True)),
                ('geo_metadata', models.JSONField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('last_interaction_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_core.tenantinfo')),
            ],
        ),
        migrations.DeleteModel(
            name='WhatsAppOrderSession',
        ),
    ]
