# Generated by Django 5.2.4 on 2025-07-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_customer_tenant_deliverypartner_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
