# Generated by Django 5.2.4 on 2025-07-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_customer_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location_coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='meta',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
