# Generated by Django 5.2.5 on 2025-08-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='components',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
