# Generated by Django 5.2.5 on 2025-09-04 13:19

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_core', '0009_tenantinfo_meta_tenantinfo_petpooja_access_token_and_more'),
        ('orders', '0008_customeraddress_components'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('petpooja_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddonItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('petpooja_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemAddonGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('petpooja_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('petpooja_addon_id', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('P', 'Percentage'), ('F', 'Fixed')], default='P', max_length=1)),
                ('rate_display', models.CharField(max_length=16)),
                ('petpooja_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantPlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='petpooja', max_length=20)),
                ('rest_id', models.CharField(max_length=64)),
                ('app_key', models.CharField(max_length=128)),
                ('app_secret', models.CharField(max_length=256)),
                ('access_token', models.CharField(max_length=512)),
                ('callback_url', models.URLField(blank=True, null=True)),
                ('meta', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='VariantTaxMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='chatsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='petpooja_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='menuitemvariant',
            name='gst_liability',
            field=models.CharField(choices=[('vendor', 'vendor'), ('restaurant', 'restaurant')], default='restaurant', max_length=16),
        ),
        migrations.AddField(
            model_name='menuitemvariant',
            name='petpooja_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='advanced_order',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='order',
            name='callback_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_charges',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('P', 'Percent'), ('F', 'Fixed')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='enable_delivery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('H', 'Home'), ('P', 'Parcel'), ('D', 'Dine-in')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='packing_charges',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='preorder_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='preorder_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='urgent_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='urgent_time_mins',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='gst_liability',
            field=models.CharField(choices=[('vendor', 'vendor'), ('restaurant', 'restaurant')], default='restaurant', max_length=16),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_tax_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='petpooja_item_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='petpooja_variant_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.menuitemvariant'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='session_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='meta',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='platformwebhooklog',
            name='source',
            field=models.CharField(choices=[('zomato', 'Zomato'), ('swiggy', 'Swiggy'), ('whatsapp', 'Whatsapp'), ('pidge', 'Pidge'), ('petpooja', 'Petpooja')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'created_at'], name='orders_orde_tenant__8eff50_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'customer', 'created_at'], name='orders_orde_tenant__436336_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'order_status'], name='orders_orde_tenant__503d01_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'payment_status'], name='orders_orde_tenant__f70ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'source', 'created_at'], name='orders_orde_tenant__d6625e_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatsession',
            constraint=models.UniqueConstraint(fields=('tenant', 'session_id'), name='uniq_session_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('telegram_id__isnull', False), models.Q(('telegram_id', ''), _negated=True)), fields=('tenant', 'telegram_id'), name='uniq_telegram_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('phone__isnull', False), models.Q(('phone', ''), _negated=True)), fields=('tenant', 'phone'), name='uniq_phone_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='menuitemvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('petpooja_id__isnull', False), models.Q(('petpooja_id', ''), _negated=True)), fields=('menu_item', 'petpooja_id'), name='uniq_pp_variant_per_item'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('external_order_id__isnull', False), models.Q(('external_order_id', ''), _negated=True)), fields=('tenant', 'external_order_id'), name='uniq_external_order_per_tenant'),
        ),
        migrations.AddField(
            model_name='addongroup',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_core.tenantinfo'),
        ),
        migrations.AddField(
            model_name='addonitem',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='orders.addongroup'),
        ),
        migrations.AddField(
            model_name='itemaddongroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.addongroup'),
        ),
        migrations.AddField(
            model_name='itemaddongroup',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_groups', to='orders.menuitem'),
        ),
        migrations.AddField(
            model_name='itemaddongroup',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_core.tenantinfo'),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_core.tenantinfo'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.menucategory'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(condition=models.Q(('petpooja_id__isnull', False), models.Q(('petpooja_id', ''), _negated=True)), fields=('tenant', 'petpooja_id'), name='uniq_pp_item_per_tenant'),
        ),
        migrations.AddField(
            model_name='orderitemaddon',
            name='addon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.addonitem'),
        ),
        migrations.AddField(
            model_name='orderitemaddon',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='tax',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_core.tenantinfo'),
        ),
        migrations.AddField(
            model_name='tenantplatformconfig',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pp_config', to='chatbot_core.tenantinfo'),
        ),
        migrations.AddField(
            model_name='varianttaxmap',
            name='tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.tax'),
        ),
        migrations.AddField(
            model_name='varianttaxmap',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='orders.menuitemvariant'),
        ),
        migrations.AddConstraint(
            model_name='addongroup',
            constraint=models.UniqueConstraint(condition=models.Q(('petpooja_id__isnull', False), models.Q(('petpooja_id', ''), _negated=True)), fields=('tenant', 'petpooja_id'), name='uniq_pp_addon_group_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='addonitem',
            constraint=models.UniqueConstraint(condition=models.Q(('petpooja_id__isnull', False), models.Q(('petpooja_id', ''), _negated=True)), fields=('group', 'petpooja_id'), name='uniq_pp_addon_item_per_group'),
        ),
        migrations.AlterUniqueTogether(
            name='itemaddongroup',
            unique_together={('item', 'group')},
        ),
        migrations.AddConstraint(
            model_name='menucategory',
            constraint=models.UniqueConstraint(condition=models.Q(('petpooja_id__isnull', False), models.Q(('petpooja_id', ''), _negated=True)), fields=('tenant', 'petpooja_id'), name='uniq_pp_category_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='tax',
            constraint=models.UniqueConstraint(condition=models.Q(('petpooja_id__isnull', False), models.Q(('petpooja_id', ''), _negated=True)), fields=('tenant', 'petpooja_id'), name='uniq_pp_tax_per_tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='varianttaxmap',
            unique_together={('variant', 'tax')},
        ),
    ]
