# Generated by Django 5.2.5 on 2025-09-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_addongroup_addonitem_itemaddongroup_menucategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantplatformconfig',
            name='access_token',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='tenantplatformconfig',
            name='app_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='tenantplatformconfig',
            name='app_secret',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='tenantplatformconfig',
            name='rest_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
