# Generated by Django 5.2.6 on 2025-09-21 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_core', '0012_alter_tenantjsondoc_dtype'),
        ('orders', '0010_alter_tenantplatformconfig_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='MenuCatalogMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_preferences', models.JSONField(blank=True, default=dict)),
                ('allergens', models.JSONField(blank=True, default=dict)),
                ('preparation', models.JSONField(blank=True, default=dict)),
                ('nutrition', models.JSONField(blank=True, default=dict)),
                ('explore_options', models.JSONField(blank=True, default=dict)),
                ('menu_category', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu_catalog_meta', to='chatbot_core.tenantinfo')),
            ],
        ),
    ]
