# Generated by Django 5.2.6 on 2025-09-21 20:35

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_core', '0012_alter_tenantjsondoc_dtype'),
        ('orders', '0011_menuitem_meta_menucatalogmeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
        migrations.AddConstraint(
            model_name='menucategory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('tenant'), name='uniq_category_name_per_tenant_ci'),
        ),
        migrations.AddConstraint(
            model_name='menucategory',
            constraint=models.CheckConstraint(condition=models.Q(('name__in', ['Ice cream', 'Desserts'])), name='menucategory_name_allowed'),
        ),
    ]
