# Generated by Django 5.2.6 on 2025-09-22 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_menuitem_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucatalogmeta',
            name='menu_category',
        ),
        migrations.AddField(
            model_name='menucatalogmeta',
            name='flavor_profile',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menucatalogmeta',
            name='ingredients',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='menucatalogmeta',
            name='menu_item',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_meta', to='orders.menuitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menucatalogmeta',
            name='pairings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='menucatalogmeta',
            name='recommendations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='menucatalogmeta',
            name='source_quality',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='menucatalogmeta',
            name='specialty_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='quantity',
            field=models.IntegerField(default=10),
        ),
    ]
