# Generated by Django 5.2.6 on 2025-09-22 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_menucatalogmeta_menu_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucatalogmeta',
            name='tenant',
        ),
    ]
