# Generated by Django 5.2.7 on 2025-10-05 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_remove_menucatalogmeta_tenant'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chatsession',
            name='uniq_session_per_tenant',
        ),
    ]
