# Generated by Django 5.2.17 on 2026-09-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_generalized_menu_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonitem',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='addonitem',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='addonitem',
            name='max_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='addonitem',
            name='min_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='itemaddongroup',
            name='max_selections',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='itemaddongroup',
            name='min_selections',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemaddongroup',
            name='variant_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='menuitemvariant',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
