# Generated by Django 5.2.17 on 2026-09-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_checkout_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantplatformconfig',
            name='tenant',
        ),
        migrations.RemoveConstraint(
            model_name='addongroup',
            name='uniq_pp_addon_group_per_tenant',
        ),
        migrations.RemoveConstraint(
            model_name='addonitem',
            name='uniq_pp_addon_item_per_group',
        ),
        migrations.RemoveConstraint(
            model_name='menucategory',
            name='uniq_pp_category_per_tenant',
        ),
        migrations.RemoveConstraint(
            model_name='menuitem',
            name='uniq_pp_item_per_tenant',
        ),
        migrations.RemoveConstraint(
            model_name='menuitemvariant',
            name='uniq_pp_variant_per_item',
        ),
        migrations.RemoveConstraint(
            model_name='tax',
            name='uniq_pp_tax_per_tenant',
        ),
        migrations.RemoveField(
            model_name='addongroup',
            name='petpooja_id',
        ),
        migrations.RemoveField(
            model_name='addonitem',
            name='petpooja_id',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='petpooja_id',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='petpooja_id',
        ),
        migrations.RemoveField(
            model_name='menuitemvariant',
            name='petpooja_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='petpooja_item_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='petpooja_variant_id',
        ),
        migrations.RemoveField(
            model_name='orderitemaddon',
            name='petpooja_addon_id',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='petpooja_id',
        ),
        migrations.AlterField(
            model_name='platformwebhooklog',
            name='source',
            field=models.CharField(choices=[('zomato', 'Zomato'), ('swiggy', 'Swiggy'), ('whatsapp', 'Whatsapp'), ('pidge', 'Pidge')], max_length=20),
        ),
        migrations.DeleteModel(
            name='TenantPlatformConfig',
        ),
    ]
