# Generated by Django 5.2.17 on 2026-09-21 18:48

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_retire_simulator_checkout'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='menuitemvariant',
            name='uniq_variant_label_per_item_ci',
        ),
        migrations.AddField(
            model_name='menuitemvariant',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='menuitemvariant',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('size'), models.F('menu_item'), condition=models.Q(('is_available', True)), name='uniq_variant_label_per_item_ci'),
        ),
    ]
